### ISSUE TITLE
advanced_platform_detection is not compatible with Gradle Plugin

### ISSUE THREAD

**Issue by Lmmerciano** [esmaeil-ahmadipour/platform_detector#1]
I am receiving a build error, when I run emulator without debugging cause by the advanced_platform_detection.

![build error](https://github.com/esmaeil-ahmadipour/platform_detector/assets/98420196/5bb44ab1-c1a9-49e6-9cae-6f97e0ef6232)

I am using  the  Kotlin version 1.7.10 and I have the jetbrains plugin as same as the kotlin_version. I also change the version to 1.6.20, 1.9.10. I also hard coded the version number inside of the gradle plugin 
Here is the buildscript
![kotlin build](https://github.com/esmaeil-ahmadipour/platform_detector/assets/98420196/70f474b3-ecba-41e1-bf02-3a849d9173f8)

**Comment by esmaeil-ahmadipour** [comment]
Hi @Lmmerciano  , this repository used for [platform_detector](https://pub.dev/packages/platform_detector) on pub.dev and cover issue for [platform_detector](https://pub.dev/packages/platform_detector) package . 

Your question is about another package. Please report this issue to the `advanced_platform_detection` package.
